
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
      public static final int EOF = 0;
      public static final int CLASS = 1;
      public static final int PUBLIC = 2;
      public static final int STATIC = 3;
      public static final int VOID = 4;
      public static final int MAIN = 5;
      public static final int LPAREN = 6;
      public static final int STRING = 7;
      public static final int LCOCHETE = 8;
      public static final int RCOCHETE = 9;
      public static final int RPAREN = 10;
      public static final int LCHAVES = 11;
      public static final int RCHAVES = 12;
      public static final int EXTENDS = 13;
      public static final int SCOLON = 14;
      public static final int VIRGULA = 15;
      public static final int RETURN = 16;
      public static final int INTEGER = 17;
      public static final int BOOLEANO = 18;
      public static final int IF = 19;
      public static final int ELSE = 20;
      public static final int WHILE = 21;
      public static final int SYSO = 22;
      public static final int ASSIGN = 23;
      public static final int AND = 24;
      public static final int LESS = 25;
      public static final int PLUS = 26;
      public static final int MINUS = 27;
      public static final int MULTI = 28;
      public static final int DOT = 29;
      public static final int LENGTH = 30;
      public static final int INTEGER_LITERAL = 31;
      public static final int TRUE = 32;
      public static final int FALSE = 33;
      public static final int THIS = 34;
      public static final int NEW = 35;
      public static final int NEGATION = 36;
      public static final int IDENTIFIER = 37;
      public static final int error = 38;

  public static final String[] terminalNames = new String[] {
			"EOF",
			"RPAREN",
			"LCHAVES",
			"RCHAVES",
			"EXTENDS",
			"SCOLON",
			"VIRGULA",
			"RETURN",
			"INTEGER",
			"BOOLEANO",
			"IF",
			"ELSE",
			"WHILE",
			"SYSO",
			"ASSIGN",
			"AND",
			"LESS",
			"PLUS",
			"MINUS",
			"MULTI",
			"DOT",
			"LENGTH",
			"INTEGER_LITERAL",
			"TRUE",
			"FALSE",
			"THIS",
			"NEW",
			"NEGATION",
			"IDENTIFIER",
            "ERROR"
  };
}

